site_name: 吴培泽的个人博客
site_url: https://wupeize.com
site_author: 吴培泽
site_description: 吴培泽的个人博客

theme:
  name: material
  features:
    - navigation.tabs               # 启用选项卡
    - navigation.tabs.sticky        # 粘性导航选项卡

# Plugins
plugins:
  - offline
  - privacy
  - search

extra:
  version:
    default: stable
  homepage: https://wupeize.com
  generator: false

copyright: COPYRIGHT &copy; 2016-2025 WUPEIZE.COM