site_name: 吴培泽的个人博客
site_url: https://wupeize.com

theme:
  name: material
  features:
    - navigation.tabs               # 启用选项卡
    - navigation.tabs.sticky        # 粘性导航选项卡


plugins:
  - offline
  - search

extra:
  generator: false

copyright: COPYRIGHT &copy; 2016-2025 WUPEIZE.COM