name: Build Deploy GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  Build-Mkdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Cache Dependencies
        id: mkdocs-material
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
        if: steps.mkdocs-material.outputs.cache-hit != 'true'

#      - name: Upload to GitHub Pages
#        uses: actions/upload-pages-artifact@v4
#        with:
#          path: site



